name: sample-laravel-api
services:
- build_command: |-
    php artisan migrate --force
    php artisan db:seed --force
  environment_slug: php
  envs:
  - key: DB_CONNECTION
    scope: RUN_TIME
    value: sqlite
  - key: APP_ENV
    scope: RUN_TIME
    value: development
  - key: APP_URL
    scope: RUN_TIME
    value: ${APP_URL}
  - key: APP_DEBUG
    scope: RUN_TIME
    value: "true"
  github:
    branch: master
    deploy_on_push: true
    repo: digitalocean/sample-laravel-api
  name: sample-laravel-api
